### ISSUE TITLE
Do we need to consider all the roles from trips-web output for matching?

### ISSUE THREAD

**Issue by sidsvash26** [RocNLP/447Project2#1]
The trips web-output has many roles which don't have any id, for example: 'LEX', 'PUNCTYPE' etc.  Are we expected to have these roles in the pattern_graph as well? 

Consider the below partial output from trips-web:
```
trips_web_output =
 {'V1534551': {'end': 10,
  'id': 'V1534551',
  'indicator': 'THE',
  'roles': {'LEX': 'BOY'},
  'start': 2,
  'type': 'MALE-CHILD',
  'word': 'BOY'},
 'V1534557': {'end': 24,
  'id': 'V1534557',
  'indicator': 'F',
  'roles': {'AFFECTED': '#V1534568',
   'AGENT': '#V1534551',
   'LEX': 'PUSHED',
   'TENSE': 'PAST'},
  'start': 2,
  'type': 'PUSH',
  'word': 'PUSH'},
 'V1534568': {'end': 24,
  'id': 'V1534568',
  'indicator': 'THE',
  'roles': {'LEX': 'BOX'},
  'start': 17,
  'type': 'BOX',
  'word': 'BOX'},
 'V1534698': {'end': 25,
  'id': 'V1534698',
  'indicator': 'SPEECHACT',
  'roles': {'CONTENT': '#V1534557', 'LEX': 'PUSHED', 'PUNCTYPE': 'DECL'},
  'start': 2,
  'type': 'SA_TELL',
  'word': None},
 'root': 'V1534698'}
```
and consider the following pattern_graph: 
```
pattern_graph =  {
    "root":"APPLY-FORCE",
    "agent":{"root": "animal"},
   "lex": {"root": "pushed"}
}

```
Is the above pattern_graph a valid input? As in, do we also need to take care of the "lex" role? I'm asking this because right now I'm assuming that the pattern_graph would have only roles which have some id `(#V.....)` in the trips_web_output. So, for example, 
content has an id:  'CONTENT': '#V1534557',
agent has an id:  'AGENT': '#V1534551',
affected has an id: 'AFFECTED': '#V1534568',

but 'LEX' has no id. Similarly, 'PUNCTYPE', and 'TENSE' have no id. I'm just assuming we won't have these as inputs in the pattern_graph i.e. the pattern-graph I've defined above is invalid because it contains "lex" as a role. Please let me know if this assumption is correct.

**Comment by sidsvash26** [comment]
Also, is it okay to assume that all the IDs will start with a `#` ?

**Comment by mrmechko** [comment]
1. All the IDs will start with a `#`
2. the above pattern is valid, but I won't be testing matches on roles that don't connect two nodes.  So you don't have to match `LEX` or `PUNCTYPE` etc.   That being said,  being able to match, say, `indicator` might be very useful.
